echo "__      _(_)/ _(_)___| | _(_|_)"
echo "\ \ /\ / / | |_| / __| |/ / | |"
echo " \ V  V /| |  _| \__ \   <| | |"
echo "  \_/\_/ |_|_| |_|___/_|\_\_|_|"
echo "this program coded by sm1l3 and w3s7"
echo "we hacker crew is ptestation"
echo "we are haktvist"
echo "this module is master of wifi hacking tool"
echo "instagram adress ptestation"
netdiscover
echo "good by :))"
